### PR TITLE
delete food route

### PR DESCRIPTION
**Pull request by zeinjendeya**
- created a delete query that takes the food id, the user id, and the category id.
- created a controller to delete the selected food
- added route to the router

#42

### CODE REVIEW

**Review by khamis-hesham — APPROVED** [review]

**Comment by tomduggan85** [comment]
Looks good to me!

**Comment by zeinjendeya** [comment]
> Looks good to me!

thanks!

**Review by hassanelnajjar — DISMISSED** [review]
You need to check the date of delete.

**Review by hassanelnajjar — APPROVED** [review]
You need to check the date of delete.

**Review by khamis-hesham — APPROVED** [review]

**Review by lina-jamal — APPROVED** [review]

**Pull request merged**
